apiVersion: v1
kind: Pod
metadata:
  name: nginx-v1
  labels:
    app: nginx-v1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
      - name: config
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
  volumes:
    - name: html
      configMap:
        name: v1-html
    - name: config
      configMap:
        name: nginx-config
