apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - name: config
        mountPath: /etc/nginx/nginx.conf
        subPath: proxy.conf
  volumes:
    - name: config
      configMap:
        name: proxy-config